# Generated by Django 4.0.4 on 2022-04-27 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('website', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Beer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50)),
                ('style', models.CharField(blank=True, choices=[('Lager', 'Lager'), ('Stout', 'Stout'), ('IPA', 'IPA'), ('Non alcohol', 'Non alcohol')], max_length=11, null=True)),
                ('alc_volume', models.FloatField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=4)),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beer_app.producer')),
            ],
        ),
    ]
