# Generated by Django 4.0.4 on 2022-04-28 17:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beer_app', '0003_beer_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beer',
            name='alc_volume',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)]),
        ),
    ]
