# Generated by Django 4.0.4 on 2022-04-28 18:31

import beerstore.beer_app.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beer_app', '0004_alter_beer_alc_volume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beer',
            name='brand',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(2), beerstore.beer_app.models.only_letters_numbers_underscores_validator]),
        ),
    ]
