# Generated by Django 4.0.4 on 2022-04-29 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beer_app', '0005_alter_beer_brand'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeerDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='beer',
            name='beerdescription',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='beer_app.beerdescription'),
        ),
    ]
