# Generated by Django 4.0.4 on 2022-04-29 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beer_app', '0006_beerdescription_beer_beerdescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beer',
            name='beerdescription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='beer_app.beerdescription'),
        ),
    ]
